// Get the modal
    var modal = document.getElementById("myModal");

    // Get the <span> element that closes the modal
    var span = document.getElementsByClassName("close")[0];

    // When the user clicks the button, open the modal 
    function showPopup(muscle) {
    var muscleType = document.getElementById("muscle-type");
    var a;
    modal.style.display = "block";
    document.getElementById("workout1").innerHTML = '';
    document.getElementById("workout2").innerHTML = '';
    document.getElementById("workout3").innerHTML = '';
    document.getElementById("workout4").innerHTML = '';
    document.getElementById("workout5").innerHTML = '';
    switch (muscle) 
    {
        case 'front-trap-a':
            muscleType.innerHTML = 'Traps';
            a = document.getElementById('workout1');
            a.innerHTML = "Seated Dumbell Shrugs";
            a.href = "https://youtu.be/2mp7RQm74G0";
            a.target = '_blank';
            linebreak = document.createElement("br");
            a.appendChild(linebreak);
            a = document.getElementById('workout2');
            a.innerHTML = "Standing Smith Machine Shrugs";
            a.href = "https://www.youtube.com/watch?v=137KPCKrG88";
            break;
        case 'front-trap-b':
            muscleType.innerHTML = 'Traps';
            a = document.getElementById('workout1');
            a.innerHTML = "Seated Dumbell Shrugs";
            a.href = "https://youtu.be/2mp7RQm74G0";
            a.target = '_blank';
            linebreak = document.createElement("br");
            a.appendChild(linebreak);
            a = document.getElementById('workout2');
            a.innerHTML = "Standing Smith Machine Shrugs";
            a.href = "https://www.youtube.com/watch?v=137KPCKrG88";
            break;
        case 'front-delt-a':
            muscleType.innerHTML = 'Shoulders';
            a = document.getElementById('workout1');
            a.innerHTML = "Seated Dumbell Shoulder Press";
            a.href = "https://youtu.be/0JfYxMRsUCQ";
            a.target = '_blank';
            linebreak = document.createElement("br");
            a.appendChild(linebreak);
            a = document.getElementById('workout2');
            a.innerHTML = "Side Lateral Raise";
            a.href = "https://youtu.be/3VcKaXpzqRo?t=15";
            a.target = '_blank';
            linebreak = document.createElement("br");
            a.appendChild(linebreak);
            a = document.getElementById('workout3');
            a.innerHTML = "Dumbell Bent-Over Raise";
            a.href = "https://youtu.be/ttvfGg9d76c?t=10";
            a.target = '_blank';
            linebreak = document.createElement("br");
            a.appendChild(linebreak);
            a = document.getElementById('workout4');
            a.innerHTML = "Arnold Press";
            a.href = "https://youtu.be/3ml7BH7mNwQ";
            a.target = '_blank';
            break;
        case 'front-delt-b':
        muscleType.innerHTML = 'Shoulders';
            a = document.getElementById('workout1');
            a.innerHTML = "Seated Dumbell Shoulder Press";
            a.href = "https://youtu.be/0JfYxMRsUCQ";
            a.target = '_blank';
            linebreak = document.createElement("br");
            a.appendChild(linebreak);
            a = document.getElementById('workout2');
            a.innerHTML = "Side Lateral Raise";
            a.href = "https://youtu.be/3VcKaXpzqRo?t=15";
            a.target = '_blank';
            linebreak = document.createElement("br");
            a.appendChild(linebreak);
            a = document.getElementById('workout3');
            a.innerHTML = "Dumbell Bent-Over Raise";
            a.href = "https://youtu.be/ttvfGg9d76c?t=10";
            a.target = '_blank';
            linebreak = document.createElement("br");
            a.appendChild(linebreak);
            a = document.getElementById('workout4');
            a.innerHTML = "Arnold Press";
            a.href = "https://youtu.be/3ml7BH7mNwQ";
            a.target = '_blank';
            break;
        case 'pecs':
            muscleType.innerHTML = 'Pecs';
            a = document.getElementById('workout1');
            a.innerHTML = "Bench Press";
            a.href = "https://youtu.be/rT7DgCr-3pg?t=10";
            a.target = '_blank';
            linebreak = document.createElement("br");
            a.appendChild(linebreak);
            a = document.getElementById('workout2');
            a.innerHTML = "Dumbell Flys";
            a.href = "https://youtu.be/kfTgKkZJnIQ";
            a.target = '_blank';
            linebreak = document.createElement("br");
            a.appendChild(linebreak);
            a = document.getElementById('workout3');
            a.innerHTML = "Incline Dumbell Press";
            a.href = "https://youtu.be/8iPEnn-ltC8?t=10";
            a.target = '_blank';
            linebreak = document.createElement("br");
            a.appendChild(linebreak);
            a = document.getElementById('workout4');
            a.innerHTML = "Low Cable Chest Fly";
            a.href = "https://youtu.be/M1N804yWA-8?t=16";
            a.target = '_blank';
            break;
        case 'left-bicep':
            muscleType.innerHTML = 'Biceps';
            a = document.getElementById('workout1');
            a.innerHTML = "Barbell Curl";
            a.href = "https://youtu.be/FAEWpmb9YQs";
            a.target = '_blank';
            linebreak = document.createElement("br");
            a.appendChild(linebreak);
            a = document.getElementById('workout2');
            a.innerHTML = "Preacher Curl";
            a.href = "https://youtu.be/1-xvtHS9PsU";
            a.target = '_blank';
            linebreak = document.createElement("br");
            a.appendChild(linebreak);
            a = document.getElementById('workout3');
            a.innerHTML = "Hammer Curl";
            a.href = "https://youtu.be/zC3nLlEvin4?t=15";
            a.target = '_blank';
            break;
        case 'right-bicep':
            muscleType.innerHTML = 'Biceps';
            a = document.getElementById('workout1');
            a.innerHTML = "Barbell Curl";
            a.href = "https://youtu.be/FAEWpmb9YQs";
            a.target = '_blank';
            linebreak = document.createElement("br");
            a.appendChild(linebreak);
            a = document.getElementById('workout2');
            a.innerHTML = "Preacher Curl";
            a.href = "https://youtu.be/1-xvtHS9PsU";
            a.target = '_blank';
            linebreak = document.createElement("br");
            a.appendChild(linebreak);
            a = document.getElementById('workout3');
            a.innerHTML = "Hammer Curl";
            a.href = "https://youtu.be/zC3nLlEvin4?t=15";
            a.target = '_blank';
            break;
        case 'front-forearm-a':
            muscleType.innerHTML = 'Forearms';
            a = document.getElementById('workout1');
            a.innerHTML = "Farmers Walk";
            a.href = "ttps://youtu.be/Fkzk_RqlYig";
            a.target = '_blank';
            linebreak = document.createElement("br");
            a.appendChild(linebreak);
            a = document.getElementById('workout2');
            a.innerHTML = "Wrist Curls";
            a.href = "https://youtu.be/qMtmHwaCmYI?t=10";
            a.target = '_blank';
            break;
        case 'front-forearm-b':
            muscleType.innerHTML = 'Forearms';
            a = document.getElementById('workout1');
            a.innerHTML = "Farmers Walk";
            a.href = "ttps://youtu.be/Fkzk_RqlYig";
            a.target = '_blank';
            linebreak = document.createElement("br");
            a.appendChild(linebreak);
            a = document.getElementById('workout2');
            a.innerHTML = "Wrist Curls";
            a.href = "https://youtu.be/qMtmHwaCmYI?t=10";
            a.target = '_blank';
            break;
        case 'obliques':
            muscleType.innerHTML = 'Obliques';
            a = document.getElementById('workout1');
            a.innerHTML = "Crunches";
            a.href = "https://youtu.be/MKmrqcoCZ-M";
            a.target = '_blank';
            linebreak = document.createElement("br");
            a.appendChild(linebreak);
            a = document.getElementById('workout2');
            a.innerHTML = "Plank";
            a.href = "https://youtu.be/pSHjTRCQxIw?t=3";
            a.target = '_blank';
            linebreak = document.createElement("br");
            a.appendChild(linebreak);
            a = document.getElementById('workout3');
            a.innerHTML = "Russian Twist";
            a.href = "https://youtu.be/wkD8rjkodUI";
            a.target = '_blank';
            break;
        case 'left-quad':
            muscleType.innerHTML = 'Quads';
            a = document.getElementById('workout1');
            a.innerHTML = "Squat";
            a.href = "https://youtu.be/nEQQle9-0NA";
            a.target = '_blank';
            linebreak = document.createElement("br");
            a.appendChild(linebreak);
            a = document.getElementById('workout2');
            a.innerHTML = "Leg Press";
            a.href = "https://youtu.be/IZxyjW7MPJQ";
            a.target = '_blank';
            linebreak = document.createElement("br");
            a.appendChild(linebreak);
            a = document.getElementById('workout3');
            a.innerHTML = "Leg Extension";
            a.href = "https://youtu.be/YyvSfVjQeL0";
            a.target = '_blank';
            break;
        case 'right-quad':
            muscleType.innerHTML = 'Quads';
            a = document.getElementById('workout1');
            a.innerHTML = "Squat";
            a.href = "https://youtu.be/nEQQle9-0NA";
            a.target = '_blank';
            linebreak = document.createElement("br");
            a.appendChild(linebreak);
            a = document.getElementById('workout2');
            a.innerHTML = "Leg Press";
            a.href = "https://youtu.be/IZxyjW7MPJQ";
            a.target = '_blank';
            linebreak = document.createElement("br");
            a.appendChild(linebreak);
            a = document.getElementById('workout3');
            a.innerHTML = "Leg Extension";
            a.href = "https://youtu.be/YyvSfVjQeL0";
            a.target = '_blank';
            break;
        case 'front-calf-a':
            muscleType.innerHTML = 'Calves';
            a = document.getElementById('workout1');
            a.innerHTML = "Standing Calf Raises";
            a.href = "https://youtu.be/YMmgqO8Jo-k?t=15";
            a.target = '_blank';
            linebreak = document.createElement("br");
            a.appendChild(linebreak);
            a = document.getElementById('workout2');
            a.innerHTML = "Seated Calf Raises";
            a.href = "https://youtu.be/E4ktXrJZUMg";
            a.target = '_blank';
            break;
        case 'front-calf-b':
            muscleType.innerHTML = 'Calves';
            a = document.getElementById('workout1');
            a.innerHTML = "Standing Calf Raises";
            a.href = "https://youtu.be/YMmgqO8Jo-k?t=15";
            a.target = '_blank';
            linebreak = document.createElement("br");
            a.appendChild(linebreak);
            a = document.getElementById('workout2');
            a.innerHTML = "Seated Calf Raises";
            a.href = "https://youtu.be/E4ktXrJZUMg";
            a.target = '_blank';
            break;

        case 'back-trap-a':
            muscleType.innerHTML = 'Traps';
            a = document.getElementById('workout1');
            a.innerHTML = "Seated Dumbell Shrugs";
            a.href = "https://youtu.be/2mp7RQm74G0";
            a.target = '_blank';
            linebreak = document.createElement("br");
            a.appendChild(linebreak);
            a = document.getElementById('workout2');
            a.innerHTML = "Standing Smith Machine Shrugs";
            a.href = "https://www.youtube.com/watch?v=137KPCKrG88";
            break;
        case 'back-trap-b':
            muscleType.innerHTML = 'Traps (Mid-Back)';
            a = document.getElementById('workout1');
            a.innerHTML = "Deadlift";
            a.href = "";
            a.target = '_blank';
            linebreak = document.createElement("br");
            a.appendChild(linebreak);
            a = document.getElementById('workout2');
            a.innerHTML = "Seated Cable Row";
            a.href = "";
            a.target = '_blank';
            linebreak = document.createElement("br");
            a.appendChild(linebreak);
            a = document.getElementById('workout3');
            a.innerHTML = "Dumbell Row";
            a.href = "";
            a.target = '_blank';
            break;
        case 'left-lats':
            muscleType.innerHTML = 'Lats';
            a = document.getElementById('workout1');
            a.innerHTML = "Bent Over Barbell Row";
            a.href = "";
            a.target = '_blank';
            linebreak = document.createElement("br");
            a.appendChild(linebreak);
            a = document.getElementById('workout2');
            a.innerHTML = " Lat Pulldown";
            a.href = "";
            a.target = '_blank';
            linebreak = document.createElement("br");
            a.appendChild(linebreak);
            a = document.getElementById('workout3');
            a.innerHTML = "Pull Ups";
            a.href = "";
            a.target = '_blank';
            break;
        case 'right-lats':
            muscleType.innerHTML = 'Lats';
            a = document.getElementById('workout1');
            a.innerHTML = "Bent Over Barbell Row";
            a.href = "";
            a.target = '_blank';
            linebreak = document.createElement("br");
            a.appendChild(linebreak);
            a = document.getElementById('workout2');
            a.innerHTML = " Lat Pulldown";
            a.href = "";
            a.target = '_blank';
            linebreak = document.createElement("br");
            a.appendChild(linebreak);
            a = document.getElementById('workout3');
            a.innerHTML = "Pull Ups";
            a.href = "";
            a.target = '_blank';
            break;
        case 'back-delt-a':
        muscleType.innerHTML = 'Shoulders';
            a = document.getElementById('workout1');
            a.innerHTML = "Seated Dumbell Shoulder Press";
            a.href = "https://youtu.be/0JfYxMRsUCQ";
            a.target = '_blank';
            linebreak = document.createElement("br");
            a.appendChild(linebreak);
            a = document.getElementById('workout2');
            a.innerHTML = "Side Lateral Raise";
            a.href = "https://youtu.be/3VcKaXpzqRo?t=15";
            a.target = '_blank';
            linebreak = document.createElement("br");
            a.appendChild(linebreak);
            a = document.getElementById('workout3');
            a.innerHTML = "Dumbell Bent-Over Raise";
            a.href = "https://youtu.be/ttvfGg9d76c?t=10";
            a.target = '_blank';
            linebreak = document.createElement("br");
            a.appendChild(linebreak);
            a = document.getElementById('workout4');
            a.innerHTML = "Arnold Press";
            a.href = "https://youtu.be/3ml7BH7mNwQ";
            a.target = '_blank';
            break;
        case 'back-delt-b':
            muscleType.innerHTML = 'Shoulders';
            a = document.getElementById('workout1');
            a.innerHTML = "Seated Dumbell Shoulder Press";
            a.href = "https://youtu.be/0JfYxMRsUCQ";
            a.target = '_blank';
            linebreak = document.createElement("br");
            a.appendChild(linebreak);
            a = document.getElementById('workout2');
            a.innerHTML = "Side Lateral Raise";
            a.href = "https://youtu.be/3VcKaXpzqRo?t=15";
            a.target = '_blank';
            linebreak = document.createElement("br");
            a.appendChild(linebreak);
            a = document.getElementById('workout3');
            a.innerHTML = "Dumbell Bent-Over Raise";
            a.href = "https://youtu.be/ttvfGg9d76c?t=10";
            a.target = '_blank';
            linebreak = document.createElement("br");
            a.appendChild(linebreak);
            a = document.getElementById('workout4');
            a.innerHTML = "Arnold Press";
            a.href = "https://youtu.be/3ml7BH7mNwQ";
            a.target = '_blank';
            break;
        case 'left-tricep':
            muscleType.innerHTML = 'Triceps';
            a = document.getElementById('workout1');
            a.innerHTML = "Dips";
            a.href = "";
            a.target = '_blank';
            linebreak = document.createElement("br");
            a.appendChild(linebreak);
            a = document.getElementById('workout2');
            a.innerHTML = "Cable Push Downs";
            a.href = "";
            a.target = '_blank';
            linebreak = document.createElement("br");
            a.appendChild(linebreak);
            a = document.getElementById('workout3');
            a.innerHTML = "Triceps Extensions";
            a.href = "";
            a.target = '_blank';
            break;
        case 'right-tricep':
            muscleType.innerHTML = 'Triceps';
            a = document.getElementById('workout1');
            a.innerHTML = "Dips";
            a.href = "";
            a.target = '_blank';
            linebreak = document.createElement("br");
            a.appendChild(linebreak);
            a = document.getElementById('workout2');
            a.innerHTML = "Cable Push Downs";
            a.href = "";
            a.target = '_blank';
            linebreak = document.createElement("br");
            a.appendChild(linebreak);
            a = document.getElementById('workout3');
            a.innerHTML = "Triceps Extensions";
            a.href = "";
            a.target = '_blank';
            break;
        case 'back-forearm-a':
            muscleType.innerHTML = 'Forearms';
            a = document.getElementById('workout1');
            a.innerHTML = "Farmers Walk";
            a.href = "ttps://youtu.be/Fkzk_RqlYig";
            a.target = '_blank';
            linebreak = document.createElement("br");
            a.appendChild(linebreak);
            a = document.getElementById('workout2');
            a.innerHTML = "Wrist Curls";
            a.href = "https://youtu.be/qMtmHwaCmYI?t=10";
            a.target = '_blank';
            break;
        case 'back-forearm-b':
            muscleType.innerHTML = 'Forearms';
            a = document.getElementById('workout1');
            a.innerHTML = "Farmers Walk";
            a.href = "ttps://youtu.be/Fkzk_RqlYig";
            a.target = '_blank';
            linebreak = document.createElement("br");
            a.appendChild(linebreak);
            a = document.getElementById('workout2');
            a.innerHTML = "Wrist Curls";
            a.href = "https://youtu.be/qMtmHwaCmYI?t=10";
            a.target = '_blank';
            break;
        case 'glutes':
            muscleType.innerHTML = 'Glutes';
            a = document.getElementById('workout1');
            a.innerHTML = "Glute Bridges";
            a.href = "";
            a.target = '_blank';
            linebreak = document.createElement("br");
            a.appendChild(linebreak);
            a = document.getElementById('workout2');
            a.innerHTML = "Lunges";
            a.href = "";
            a.target = '_blank';
            linebreak = document.createElement("br");
            a.appendChild(linebreak);
            a = document.getElementById('workout3');
            a.innerHTML = "Barbell Hip trust";
            a.href = "";
            a.target = '_blank';
            break;
        case 'left-hamstring':
            muscleType.innerHTML = 'Hamstring';
            a = document.getElementById('workout1');
            a.innerHTML = "Squats";
            a.href = "";
            a.target = '_blank';
            linebreak = document.createElement("br");
            a.appendChild(linebreak);
            a = document.getElementById('workout2');
            a.innerHTML = "Stiff Leg Deadlift";
            a.href = "";
            a.target = '_blank';
            linebreak = document.createElement("br");
            a.appendChild(linebreak);
            a = document.getElementById('workout3');
            a.innerHTML = "Hamstring Curl";
            a.href = "";
            a.target = '_blank';
            break;
        case 'right-hamstring':
            muscleType.innerHTML = 'Hamstring';
            muscleType.innerHTML = 'Hamstring';
            a = document.getElementById('workout1');
            a.innerHTML = "Squats";
            a.href = "";
            a.target = '_blank';
            linebreak = document.createElement("br");
            a.appendChild(linebreak);
            a = document.getElementById('workout2');
            a.innerHTML = "Stiff Leg Deadlift";
            a.href = "";
            a.target = '_blank';
            linebreak = document.createElement("br");
            a.appendChild(linebreak);
            a = document.getElementById('workout3');
            a.innerHTML = "Hamstring Curl";
            a.href = "";
            a.target = '_blank';
            break;
        case 'back-calf-a':
            muscleType.innerHTML = 'Calves';
            a = document.getElementById('workout1');
            a.innerHTML = "Standing Calf Raises";
            a.href = "https://youtu.be/YMmgqO8Jo-k?t=15";
            a.target = '_blank';
            linebreak = document.createElement("br");
            a.appendChild(linebreak);
            a = document.getElementById('workout2');
            a.innerHTML = "Seated Calf Raises";
            a.href = "https://youtu.be/E4ktXrJZUMg";
            a.target = '_blank';
            break;
        case 'back-calf-b':
            muscleType.innerHTML = 'Calves';
            a = document.getElementById('workout1');
            a.innerHTML = "Standing Calf Raises";
            a.href = "https://youtu.be/YMmgqO8Jo-k?t=15";
            a.target = '_blank';
            linebreak = document.createElement("br");
            a.appendChild(linebreak);
            a = document.getElementById('workout2');
            a.innerHTML = "Seated Calf Raises";
            a.href = "https://youtu.be/E4ktXrJZUMg";
            a.target = '_blank';
            break;        
    }
    }

    // When the user clicks on <span> (x), close the modal
    span.onclick = function() {
        modal.style.display = "none";
    }

    // When the user clicks anywhere outside of the modal, close it
    window.onclick = function(event) {
        if (event.target == modal) {
            modal.style.display = "none";
        }
    }